backend:
  name: git-gateway
  repo: jtx007/raj-portfolio-cms
  branch: main
local_backend: true
media_folder: static/assets
public_folder: /assets
media_folder_relative: true

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: pages
    label: Pages
    files:
      - label: "About"
        name: "about"
        file: "src/md/about.md"
        fields:
          - { name: info, label: info, widget: markdown }

      - label: "Contact"
        name: "Contact"
        file: "src/md/contact.md"
        fields:
          - { name: email, label: email, widget: string}
  - name: work
    label: Works
    folder: "src/works"
    create: true
    slug: "{{title}}"
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name:  work type, label: type, widget: select, options: ["Architecture", "Apparel", "Objects", "Studies", "Academia"]}
      - { name: main image, label: main image, widget: image}
      - { name: description, label: description, widget: markdown }